import type {
  Assignment,
  Lead,
  Lesson,
  Meeting,
  Offer,
  PaymentTransaction,
  Reminder,
  ReportLanguageStat,
  StudentProfile,
  StudentProgressSummary,
  StudentTimelineEvent,
  User,
} from './types';

export const workspaceUsers: User[] = [
  {
    id: 'user-admin-yunus',
    name: 'Yunus Emre',
    initials: 'YE',
    email: 'yunus@zumraakademi.com',
    phone: '+90 555 100 10 10',
    role: 'admin',
    handle: '@yunus_admin',
    title: 'Kurucu Admin',
  },
  {
    id: 'user-advisor-aylin',
    name: 'Aylin Karaca',
    initials: 'AK',
    email: 'aylin@zumraakademi.com',
    phone: '+90 555 200 20 20',
    role: 'advisor',
    handle: '@aylin_danisman',
    title: 'Eğitim Danışmanı',
  },
  {
    id: 'user-teacher-sarah',
    name: 'Sarah Lee',
    initials: 'SL',
    email: 'sarah@zumraakademi.com',
    role: 'teacher',
    handle: '@sarah_teacher',
    title: 'İngilizce Eğitmeni',
  },
  {
    id: 'user-student-zeynep',
    name: 'Zeynep Kaya',
    initials: 'ZK',
    email: 'zeynep@example.com',
    phone: '+90 555 300 30 30',
    role: 'student',
    handle: '@zeynep',
    title: 'Öğrenci',
  },
];

export const workspaceStudents: StudentProfile[] = [
  {
    id: 'student-zeynep',
    userId: 'user-student-zeynep',
    fullName: 'Zeynep Kaya',
    email: 'zeynep@example.com',
    phone: '+90 555 300 30 30',
    language: 'İngilizce',
    level: 'B1 Intermediate',
    programType: 'generalEducation',
    status: 'active',
    progress: 65,
    advisorId: 'user-advisor-aylin',
    teacherIds: ['user-teacher-sarah'],
    nextSessionAt: '2026-06-04T14:00:00+03:00',
  },
  {
    id: 'student-ayse',
    userId: 'user-student-ayse',
    fullName: 'Ayşe Demir',
    email: 'ayse.demir@example.com',
    phone: '+90 555 123 45 67',
    language: 'Almanca',
    level: 'A1 Beginner',
    programType: 'generalEducation',
    status: 'active',
    progress: 20,
    advisorId: 'user-advisor-aylin',
    teacherIds: [],
    nextSessionAt: '2026-06-03T18:00:00+03:00',
  },
  {
    id: 'student-fatma',
    userId: 'user-student-fatma',
    fullName: 'Fatma Şahin',
    email: 'fatma.sahin@example.com',
    phone: '+90 555 444 12 11',
    language: 'Arapça',
    level: 'B2 Upper',
    programType: 'generalEducation',
    status: 'active',
    progress: 85,
    advisorId: 'user-advisor-aylin',
    teacherIds: [],
    nextSessionAt: '2026-06-05T11:00:00+03:00',
  },
  {
    id: 'student-elif',
    userId: 'user-student-elif',
    fullName: 'Elif Türkmen',
    email: 'elif.turkmen@example.com',
    phone: '+90 555 222 33 44',
    language: 'İngilizce',
    level: 'A2 Elementary',
    programType: 'generalEducation',
    status: 'paused',
    progress: 40,
    advisorId: 'user-advisor-aylin',
    teacherIds: ['user-teacher-sarah'],
  },
];

export const workspaceLeads: Lead[] = [
  {
    id: 'lead-ayse',
    fullName: 'Ayşe Demir',
    email: 'ayse.demir@gmail.com',
    phone: '+90 555 123 45 67',
    interestedProgram: 'İngilizce',
    level: 'A1',
    source: 'Instagram Form',
    status: 'new',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-03T10:45:00+03:00',
    lastActivityLabel: '10 dk',
  },
  {
    id: 'lead-fatma',
    fullName: 'Fatma Kaya',
    email: 'fatma@example.com',
    phone: '+90 555 876 54 32',
    interestedProgram: 'Arapça',
    level: 'B1',
    source: 'Web Form',
    status: 'contacted',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-03T08:15:00+03:00',
    lastActivityLabel: '2 saat',
  },
  {
    id: 'lead-zeynep',
    fullName: 'Zeynep Yılmaz',
    email: 'zeynep.yilmaz@example.com',
    phone: '+90 555 999 11 22',
    interestedProgram: 'Almanca',
    level: 'A2',
    source: 'Telefon',
    status: 'offer_pending',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-02T16:30:00+03:00',
    lastActivityLabel: 'Dün',
  },
  {
    id: 'lead-selin',
    fullName: 'Selin Şahin',
    email: 'selin@example.com',
    phone: '+90 555 111 22 33',
    interestedProgram: 'Almanca',
    level: 'A1',
    source: 'Referans',
    status: 'meeting_scheduled',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-02T11:00:00+03:00',
    lastActivityLabel: 'Dün',
  },
];

export const workspaceLessons: Lesson[] = [
  {
    id: 'lesson-speaking',
    studentId: 'student-zeynep',
    teacherId: 'user-teacher-sarah',
    title: 'Speaking Practice',
    topic: 'Everyday Scenarios',
    startsAt: '2026-06-03T14:00:00+03:00',
    status: 'upcoming',
  },
  {
    id: 'lesson-grammar',
    studentId: 'student-zeynep',
    teacherId: 'user-teacher-sarah',
    title: 'Grammar Focus',
    topic: 'Perfect Tenses',
    startsAt: '2026-06-04T14:00:00+03:00',
    status: 'upcoming',
  },
  {
    id: 'lesson-listening',
    studentId: 'student-zeynep',
    teacherId: 'user-teacher-sarah',
    title: 'Listening Comprehension',
    topic: 'News Articles',
    startsAt: '2026-05-28T14:00:00+03:00',
    status: 'completed',
  },
];

export const workspaceMeetings: Meeting[] = [
  {
    id: 'meeting-ayse-intake',
    title: 'Danışmanlık - Ayşe Demir',
    leadId: 'lead-ayse',
    advisorId: 'user-advisor-aylin',
    startsAt: '2026-06-03T14:00:00+03:00',
    channel: 'zoom',
    status: 'scheduled',
    link: 'https://meet.zumraakademi.com/ayse-demir',
    qrPayload: 'zumra:meeting:meeting-ayse-intake',
  },
  {
    id: 'meeting-zeynep-level',
    title: 'Seviye Tespiti - Zeynep Kaya',
    studentId: 'student-zeynep',
    advisorId: 'user-advisor-aylin',
    teacherId: 'user-teacher-sarah',
    startsAt: '2026-06-04T14:00:00+03:00',
    channel: 'google_meet',
    status: 'scheduled',
    link: 'https://meet.zumraakademi.com/zeynep-kaya',
    qrPayload: 'zumra:meeting:meeting-zeynep-level',
  },
];

export const workspaceOffers: Offer[] = [
  {
    id: 'offer-ayse-speaking',
    title: 'İngilizce Speaking Paketi',
    leadId: 'lead-ayse',
    advisorId: 'user-advisor-aylin',
    amount: 12000,
    currency: 'TRY',
    status: 'draft',
    channels: ['email', 'whatsapp'],
  },
  {
    id: 'offer-zeynep-almanca',
    title: 'Almanca A2 6 Aylık Paket',
    leadId: 'lead-zeynep',
    advisorId: 'user-advisor-aylin',
    amount: 18000,
    currency: 'TRY',
    status: 'sent',
    channels: ['email', 'whatsapp'],
    sentAt: '2026-06-02T18:00:00+03:00',
  },
  {
    id: 'offer-zeynep-english',
    title: 'İngilizce B1 6 Aylık Paket',
    studentId: 'student-zeynep',
    advisorId: 'user-advisor-aylin',
    amount: 24000,
    currency: 'TRY',
    status: 'accepted',
    channels: ['email', 'whatsapp'],
    sentAt: '2026-05-12T14:30:00+03:00',
  },
];

export const workspacePayments: PaymentTransaction[] = [
  {
    id: 'payment-ayse-speaking',
    leadId: 'lead-ayse',
    payerName: 'Ayşe Demir',
    planKey: 'englishSixMonths',
    amount: 12000,
    currency: 'TRY',
    paidAt: '2026-06-03T14:20:00+03:00',
    status: 'paid',
  },
  {
    id: 'payment-fatma-arabic',
    leadId: 'lead-fatma',
    payerName: 'Fatma Kaya',
    planKey: 'arabicInstallment',
    amount: 2500,
    currency: 'TRY',
    paidAt: '2026-06-03T10:15:00+03:00',
    status: 'paid',
  },
  {
    id: 'payment-zeynep-german',
    leadId: 'lead-zeynep',
    payerName: 'Zeynep Yılmaz',
    planKey: 'germanInstallment',
    amount: 3000,
    currency: 'TRY',
    paidAt: '2026-06-02T16:45:00+03:00',
    status: 'pending',
  },
  {
    id: 'payment-elif-private',
    studentId: 'student-elif',
    payerName: 'Elif Türkmen',
    planKey: 'englishPrivate',
    amount: 8500,
    currency: 'TRY',
    paidAt: '2026-03-15T09:30:00+03:00',
    status: 'failed',
  },
  {
    id: 'payment-zeynep-english',
    studentId: 'student-zeynep',
    payerName: 'Zeynep Kaya',
    planKey: 'englishSixMonths',
    amount: 12000,
    currency: 'TRY',
    paidAt: '2026-05-12T15:00:00+03:00',
    status: 'paid',
  },
];

export const workspaceReportLanguageStats: ReportLanguageStat[] = [
  { language: 'İngilizce', percentage: 75, count: 1110, colorClass: 'from-[#8C6CE6] to-[#533089]' },
  { language: 'Arapça', percentage: 45, count: 320, colorClass: 'from-blue-400 to-blue-600' },
  { language: 'Almanca', percentage: 30, count: 180, colorClass: 'from-emerald-400 to-emerald-600' },
  { language: 'Fransızca', percentage: 15, count: 90, colorClass: 'from-amber-400 to-amber-600' },
];

export const workspaceStudentProgressSummaries: StudentProgressSummary[] = [
  {
    studentId: 'student-zeynep',
    overall: 65,
    completedLessons: 12,
    totalLessons: 24,
    streak: 12,
    skills: [
      { key: 'speaking', icon: 'speaking', value: 72, tone: 'brand' },
      { key: 'listening', icon: 'listening', value: 65, tone: 'blue' },
      { key: 'reading', icon: 'reading', value: 80, tone: 'emerald' },
      { key: 'writing', icon: 'writing', value: 55, tone: 'amber' },
    ],
    badges: [
      { earned: true },
      { earned: true },
      { earned: true },
      { earned: false },
      { earned: false },
    ],
  },
];

export const workspaceStudentTimelineEvents: StudentTimelineEvent[] = [
  {
    id: 'timeline-zeynep-speaking',
    studentId: 'student-zeynep',
    lessonId: 'lesson-speaking',
    noteKey: 'speakingPractice',
    homeworkState: 'assigned',
    attachmentName: 'Unit_12_Notes.pdf',
  },
  {
    id: 'timeline-zeynep-grammar',
    studentId: 'student-zeynep',
    lessonId: 'lesson-grammar',
    noteKey: 'grammarFocus',
    homeworkState: 'completed',
  },
];

export const workspaceReminders: Reminder[] = [
  {
    id: 'reminder-ayse-student',
    meetingId: 'meeting-ayse-intake',
    recipientUserId: 'user-student-ayse',
    channel: 'email',
    scheduledAt: '2026-06-03T13:00:00+03:00',
    status: 'scheduled',
  },
  {
    id: 'reminder-ayse-advisor',
    meetingId: 'meeting-ayse-intake',
    recipientUserId: 'user-advisor-aylin',
    channel: 'email',
    scheduledAt: '2026-06-03T13:00:00+03:00',
    status: 'scheduled',
  },
];

export const workspaceAssignments: Assignment[] = [
  { id: 'assignment-aylin-zeynep', advisorId: 'user-advisor-aylin', studentId: 'student-zeynep' },
  { id: 'assignment-aylin-ayse-lead', advisorId: 'user-advisor-aylin', leadId: 'lead-ayse' },
  { id: 'assignment-sarah-zeynep', teacherId: 'user-teacher-sarah', studentId: 'student-zeynep' },
];

export const workspaceSeed = {
  assignments: workspaceAssignments,
  leads: workspaceLeads,
  lessons: workspaceLessons,
  meetings: workspaceMeetings,
  offers: workspaceOffers,
  payments: workspacePayments,
  reportLanguageStats: workspaceReportLanguageStats,
  reminders: workspaceReminders,
  studentProgressSummaries: workspaceStudentProgressSummaries,
  studentTimelineEvents: workspaceStudentTimelineEvents,
  students: workspaceStudents,
  users: workspaceUsers,
};
