import type { Assignment, Lead, Lesson, Meeting, Offer, Reminder, StudentProfile, User } from './types';

export const workspaceUsers: User[] = [
  {
    id: 'user-admin-yunus',
    name: 'Yunus Emre',
    initials: 'YE',
    email: 'yunus@zumraakademi.com',
    phone: '+90 555 100 10 10',
    role: 'admin',
    handle: '@yunus_admin',
    title: 'Kurucu Admin',
  },
  {
    id: 'user-advisor-aylin',
    name: 'Aylin Karaca',
    initials: 'AK',
    email: 'aylin@zumraakademi.com',
    phone: '+90 555 200 20 20',
    role: 'advisor',
    handle: '@aylin_danisman',
    title: 'Eğitim Danışmanı',
  },
  {
    id: 'user-teacher-sarah',
    name: 'Sarah Lee',
    initials: 'SL',
    email: 'sarah@zumraakademi.com',
    role: 'teacher',
    handle: '@sarah_teacher',
    title: 'İngilizce Eğitmeni',
  },
  {
    id: 'user-student-zeynep',
    name: 'Zeynep Kaya',
    initials: 'ZK',
    email: 'zeynep@example.com',
    phone: '+90 555 300 30 30',
    role: 'student',
    handle: '@zeynep',
    title: 'Öğrenci',
  },
];

export const workspaceStudents: StudentProfile[] = [
  {
    id: 'student-zeynep',
    userId: 'user-student-zeynep',
    fullName: 'Zeynep Kaya',
    email: 'zeynep@example.com',
    phone: '+90 555 300 30 30',
    language: 'İngilizce',
    level: 'B1 Intermediate',
    status: 'active',
    progress: 65,
    advisorId: 'user-advisor-aylin',
    teacherIds: ['user-teacher-sarah'],
    nextSessionAt: '2026-06-04T14:00:00+03:00',
  },
  {
    id: 'student-ayse',
    userId: 'user-student-ayse',
    fullName: 'Ayşe Demir',
    email: 'ayse.demir@example.com',
    phone: '+90 555 123 45 67',
    language: 'Almanca',
    level: 'A1 Beginner',
    status: 'active',
    progress: 20,
    advisorId: 'user-advisor-aylin',
    teacherIds: [],
    nextSessionAt: '2026-06-03T18:00:00+03:00',
  },
  {
    id: 'student-fatma',
    userId: 'user-student-fatma',
    fullName: 'Fatma Şahin',
    email: 'fatma.sahin@example.com',
    phone: '+90 555 444 12 11',
    language: 'Arapça',
    level: 'B2 Upper',
    status: 'active',
    progress: 85,
    advisorId: 'user-advisor-aylin',
    teacherIds: [],
    nextSessionAt: '2026-06-05T11:00:00+03:00',
  },
  {
    id: 'student-elif',
    userId: 'user-student-elif',
    fullName: 'Elif Türkmen',
    email: 'elif.turkmen@example.com',
    phone: '+90 555 222 33 44',
    language: 'İngilizce',
    level: 'A2 Elementary',
    status: 'paused',
    progress: 40,
    advisorId: 'user-advisor-aylin',
    teacherIds: ['user-teacher-sarah'],
  },
];

export const workspaceLeads: Lead[] = [
  {
    id: 'lead-ayse',
    fullName: 'Ayşe Demir',
    email: 'ayse.demir@gmail.com',
    phone: '+90 555 123 45 67',
    interestedProgram: 'İngilizce',
    level: 'A1',
    source: 'Instagram Form',
    status: 'new',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-03T10:45:00+03:00',
    lastActivityLabel: '10 dk',
  },
  {
    id: 'lead-fatma',
    fullName: 'Fatma Kaya',
    email: 'fatma@example.com',
    phone: '+90 555 876 54 32',
    interestedProgram: 'Arapça',
    level: 'B1',
    source: 'Web Form',
    status: 'contacted',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-03T08:15:00+03:00',
    lastActivityLabel: '2 saat',
  },
  {
    id: 'lead-zeynep',
    fullName: 'Zeynep Yılmaz',
    email: 'zeynep.yilmaz@example.com',
    phone: '+90 555 999 11 22',
    interestedProgram: 'Almanca',
    level: 'A2',
    source: 'Telefon',
    status: 'offer_pending',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-02T16:30:00+03:00',
    lastActivityLabel: 'Dün',
  },
  {
    id: 'lead-selin',
    fullName: 'Selin Şahin',
    email: 'selin@example.com',
    phone: '+90 555 111 22 33',
    interestedProgram: 'Almanca',
    level: 'A1',
    source: 'Referans',
    status: 'meeting_scheduled',
    advisorId: 'user-advisor-aylin',
    createdAt: '2026-06-02T11:00:00+03:00',
    lastActivityLabel: 'Dün',
  },
];

export const workspaceLessons: Lesson[] = [
  {
    id: 'lesson-speaking',
    studentId: 'student-zeynep',
    teacherId: 'user-teacher-sarah',
    title: 'Speaking Practice',
    topic: 'Everyday Scenarios',
    startsAt: '2026-06-03T14:00:00+03:00',
    status: 'upcoming',
  },
  {
    id: 'lesson-grammar',
    studentId: 'student-zeynep',
    teacherId: 'user-teacher-sarah',
    title: 'Grammar Focus',
    topic: 'Perfect Tenses',
    startsAt: '2026-06-04T14:00:00+03:00',
    status: 'upcoming',
  },
  {
    id: 'lesson-listening',
    studentId: 'student-zeynep',
    teacherId: 'user-teacher-sarah',
    title: 'Listening Comprehension',
    topic: 'News Articles',
    startsAt: '2026-05-28T14:00:00+03:00',
    status: 'completed',
  },
];

export const workspaceMeetings: Meeting[] = [
  {
    id: 'meeting-ayse-intake',
    title: 'Danışmanlık - Ayşe Demir',
    leadId: 'lead-ayse',
    advisorId: 'user-advisor-aylin',
    startsAt: '2026-06-03T14:00:00+03:00',
    channel: 'zoom',
    status: 'scheduled',
    link: 'https://meet.zumraakademi.com/ayse-demir',
    qrPayload: 'zumra:meeting:meeting-ayse-intake',
  },
  {
    id: 'meeting-zeynep-level',
    title: 'Seviye Tespiti - Zeynep Kaya',
    studentId: 'student-zeynep',
    advisorId: 'user-advisor-aylin',
    teacherId: 'user-teacher-sarah',
    startsAt: '2026-06-04T14:00:00+03:00',
    channel: 'google_meet',
    status: 'scheduled',
    link: 'https://meet.zumraakademi.com/zeynep-kaya',
    qrPayload: 'zumra:meeting:meeting-zeynep-level',
  },
];

export const workspaceOffers: Offer[] = [
  {
    id: 'offer-ayse-speaking',
    title: 'İngilizce Speaking Paketi',
    leadId: 'lead-ayse',
    advisorId: 'user-advisor-aylin',
    amount: 12000,
    currency: 'TRY',
    status: 'draft',
    channels: ['email', 'whatsapp'],
  },
  {
    id: 'offer-zeynep-almanca',
    title: 'Almanca A2 6 Aylık Paket',
    leadId: 'lead-zeynep',
    advisorId: 'user-advisor-aylin',
    amount: 18000,
    currency: 'TRY',
    status: 'sent',
    channels: ['email', 'whatsapp'],
    sentAt: '2026-06-02T18:00:00+03:00',
  },
];

export const workspaceReminders: Reminder[] = [
  {
    id: 'reminder-ayse-student',
    meetingId: 'meeting-ayse-intake',
    recipientUserId: 'user-student-ayse',
    channel: 'email',
    scheduledAt: '2026-06-03T13:00:00+03:00',
    status: 'scheduled',
  },
  {
    id: 'reminder-ayse-advisor',
    meetingId: 'meeting-ayse-intake',
    recipientUserId: 'user-advisor-aylin',
    channel: 'email',
    scheduledAt: '2026-06-03T13:00:00+03:00',
    status: 'scheduled',
  },
];

export const workspaceAssignments: Assignment[] = [
  { id: 'assignment-aylin-zeynep', advisorId: 'user-advisor-aylin', studentId: 'student-zeynep' },
  { id: 'assignment-aylin-ayse-lead', advisorId: 'user-advisor-aylin', leadId: 'lead-ayse' },
  { id: 'assignment-sarah-zeynep', teacherId: 'user-teacher-sarah', studentId: 'student-zeynep' },
];

export const workspaceSeed = {
  assignments: workspaceAssignments,
  leads: workspaceLeads,
  lessons: workspaceLessons,
  meetings: workspaceMeetings,
  offers: workspaceOffers,
  reminders: workspaceReminders,
  students: workspaceStudents,
  users: workspaceUsers,
};
