bind 0.0.0.0
protected-mode yes
port 6379
appendonly yes
appendfsync everysec
save 900 1
save 300 10
save 60 10000
maxmemory-policy noeviction
dir /data
dbfilename dump.rdb
appenddirname appendonlydir
loglevel notice
